# Generated by Django 4.0.6 on 2022-10-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('merit', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.societyquestion')),
            ],
        ),
    ]
