# Generated by Django 4.0.6 on 2022-10-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_mediacontentlearning_mediacontentrequirement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaContentLearning',
            new_name='SocietyLearning',
        ),
        migrations.RenameModel(
            old_name='MediaContentRequirement',
            new_name='SocietyRequirement',
        ),
    ]
