# Generated by Django 4.0.6 on 2022-10-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humanity_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Humanity_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HumanityBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='data published')),
                ('body', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HumanityQuestion_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HumanityQuestion_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='humanity',
            name='count',
        ),
        migrations.CreateModel(
            name='HumanityAnswer_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanity.humanity_eng')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanity.humanityquestion_eng')),
            ],
        ),
        migrations.CreateModel(
            name='HumanityAnswer_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanity.humanity_cn')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanity.humanityquestion_cn')),
            ],
        ),
    ]
