# Generated by Django 4.0.6 on 2022-10-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0006_itlearning_itrequirement_delete_itresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITBoard',
        ),
    ]
