# Generated by Django 4.0.6 on 2022-10-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaContent_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaContentBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='data published')),
                ('body', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MediaContentQuestion_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MediaContentQuestion_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='MediaContentsAnswer',
            new_name='MediaContentAnswer',
        ),
        migrations.RemoveField(
            model_name='mediacontent',
            name='count',
        ),
        migrations.RemoveField(
            model_name='mediacontent',
            name='merit',
        ),
        migrations.RemoveField(
            model_name='mediacontent',
            name='result',
        ),
        migrations.RenameModel(
            old_name='MediaContentsQuestion',
            new_name='MediaContentQuestion',
        ),
        migrations.CreateModel(
            name='MediaContentAnswer_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediacontent_eng')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediacontentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MediaContentAnswer_CN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediacontent_cn')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediacontentquestion_cn')),
            ],
        ),
    ]
